// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ztlcklmzepocurmshgpk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp0bGNrbG16ZXBvY3VybXNoZ3BrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA5NzkyODEsImV4cCI6MjA2NjU1NTI4MX0.pI9vsJP3b21il9D_9GDZ2B1id1rmCgTut5SD8c9Olc8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);